# Generated by Django 4.2.11 on 2024-12-13 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='Unknown Product', help_text='Enter the product name manually for testing.', max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the price of the product.', max_digits=10)),
                ('order_id', models.CharField(default='demo_order_id', help_text='Order ID for sales and returns (restocks may not have this).', max_length=32)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('return', 'Return')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
